name: Reusable Workflow - Receive Branch and Event

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch name from upstream"
        required: true
        type: string
      event:
        description: "Triggering event from upstream"
        required: true
        type: string

jobs:
  tfc_plan:
    runs-on: ubuntu-latest
    if: |
      inputs.event == 'pull_request' ||
      (inputs.event == 'push' && inputs.branch == 'master')
    steps:
      - name: Print received inputs
        run: |
          echo "This is Terraform Cloud plan phase"
          echo "Branch: ${{ inputs.branch }}"
          echo "Event:  ${{ inputs.event }}"

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: tfc_plan
    if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,user3,group1,group2 # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the deployment."

  tfc_apply:
    runs-on: ubuntu-latest
    if: |
      inputs.branch == 'master'
    steps:
      - name: Print received inputs
        run: |
          echo "This is Terraform Cloud apply phase"
          echo "Branch: ${{ inputs.branch }}"
          echo "Event:  ${{ inputs.event }}"
